apiVersion: v1
kind: Pod
metadata:
  name: pod5
  annotations:
    io.katacontainers.config.hypervisor.kernel: "/home/core/images/vmlinuz-6.3.8-108"
spec:
  runtimeClassName: kata-qemu
  containers:
  - name: c1
    image: ubuntu
    command:
      - bash
