apiVersion: v1
kind: Pod
metadata:
  name: pod2
  annotations:
    #io.katacontainers.config.hypervisor.kernel: "/home/navadiaev/dev/linux/vmlinux"
    #io.katacontainers.config.hypervisor.kernel: "/home/navadiaev/dev/linux/arch/x86/boot/bzImage"
spec:
  runtimeClassName: kata-qemu
  containers:
  - name: c1
    image: ubuntu
    command:
      - bash
